- name: Create syspass web server directory
  ansible.builtin.file:
   state: directory
   path: "{{ syspass_directory }}"
   recurse: yes
   owner: apache
   group: apache

- name: Clone Syspass Git Project
  ansible.builtin.git:
   repo: "{{ git_repo }}"
   dest: "{{ syspass_directory }}"
   force: yes

- name: Check directory permissions
  ansible.builtin.file:
   state: directory
   owner: apache
   group: apache
   recurse: yes
   mode: 0750
   path: "{{ syspass_directory }}"


