- name: Get Mysql default root password
  ansible.builtin.shell:
    cmd: grep temporary /var/log/mysqld.log | grep root
  register: mysql_root_password

- name: Debug root password
  ansible.builtin.debug:
    msg: "{{ mysql_root_password.stdout }}"
