---
- name: Including Installation Task
  ansible.builtin.include_tasks: 
    file: installation.yml

- name: Include Directory and Permission Task
  ansible.builtin.include_tasks: 
    file: directories_and_permissions.yml

- name: Include Selinux Task
  ansible.builtin.include_tasks: 
    file: selinux.yml

- name: Include PHP Composer Task
  ansible.builtin.include_tasks: 
    file: php_composer.yml

- name: Include Mysql get root password
  ansible.builtin.include_tasks:
    file: get_temporary_mysql_root_password.yml
