---
- name: Get Customer ID
  ansible.builtin.include_tasks: 
    file: get_client_id.yml

- name: Delete Account
  ansible.builtin.include_tasks: 
    file: delete_account.yml

- name: Delete Account History
  ansible.builtin.include_tasks: 
    file: delete_account_history.yml

- name: Delete Customer from Syspass
  ansible.builtin.include_tasks: 
    file: delete_customer.yml 
